(cl:defpackage sensor_msgs_ext-msg
  (:use )
  (:export
   "<ACCELERATION>"
   "ACCELERATION"
   "<ANALOG_VOLTAGE>"
   "ANALOG_VOLTAGE"
   "<ANGULAR_VELOCITY>"
   "ANGULAR_VELOCITY"
   "<AXIS_STATE>"
   "AXIS_STATE"
   "<COVARIANCE>"
   "COVARIANCE"
   "<GNSS_FIX>"
   "GNSS_FIX"
   "<GNSS_POSITION>"
   "GNSS_POSITION"
   "<GNSS_TRACK>"
   "GNSS_TRACK"
   "<MAGNETIC_FIELD>"
   "MAGNETIC_FIELD"
   "<PROXIMITY>"
   "PROXIMITY"
   "<TEMPERATURE>"
   "TEMPERATURE"
   "<TIME_REFERENCE>"
   "TIME_REFERENCE"
  ))

